version: '3.9'

services:
  nginx:
    build: requirements/nginx
    container_name: nginx
    depends_on:
      - mariadb # depends_on can be done with a health check
    ports:
      - "443:443"

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    expose:
      - "9000"
      - "3306"
    volumes:
      - wp_data:/var/lib/wordpress
    networks:
      - inception_backend

  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    expose:
      - "3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception_backend
    env_file:
      - .env

volumes:
  db_data:
    driver: 'local'
    driver_opts:
      o: 'bind'
      type: 'none'
      device: '/home/tkruger/data/mysql'
  wp_data:
    driver: 'local'
    driver_opts:
      o: 'bind'
      type: 'none'
      device: '/home/tkruger/data/wordpress'

networks:
  inception_backend: