version: '3.9'

services:
  mariadb:
    build: requirements/mariadb
    image: mariadb
    container_name: mariadb
    expose:
      - "3306"
    volumes:
      - db_data:/var/lib/mysql:delegated
    env_file:
      - .env
    networks:
      - backend
    restart: unless-stopped

  wordpress:
    build: requirements/wordpress
    image: wordpress
    container_name: wordpress
    expose:
      - "9000"
    volumes:
      - wp_content:/var/www/html:delegated
    env_file:
      - .env
    networks:
      - backend
    depends_on:
      - mariadb # depends_on can be done with a health check
    restart: unless-stopped

  nginx:
    build: requirements/nginx
    image: nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wp_content:/var/www/html:delegated
    networks:
      - backend
    depends_on:
      - wordpress # depends_on can be done with a health check
    restart: unless-stopped

volumes:
  db_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $HOME/data/mysql_data
  wp_content:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $HOME/data/wordpress_content

networks:
  backend:
