services:
  # nginx:
  #   build:
  #     context: ./requirements/nginx/
  #     dockerfile: Dockerfile
  #   depends on:
  #     - mariadb

  mariadb:
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
    env_file: .env # should mariadb parameters be included here or in requirements/mariadb/conf/ ?
    volumes:
      - requirements/mariadb/tools/data:/var/lib/mysql # not sure about the correctnes of the paths

volumes:
  requirements/mariadb/tools/data