version: '3.9'

services:
  # nginx:
  #   build:
  #     context: ./requirements/nginx/
  #     dockerfile: Dockerfile
  #   depends on:
  #     - mariadb

  mariadb:
    build:
      context: ./requirements/mariadb/
      # image: MariaDB
      dockerfile: Dockerfile
    env_file: .env # should mariadb parameters be included here or in requirements/mariadb/conf/ ?
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: