version: '3.9'

services:
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    expose:
      - "3306"
    volumes:
      - db_data:/var/lib/mysql:delegated
    networks:
      - inception_network
    env_file:
      - .env
    # restart:
    #   - always

  wordpress:
    build: requirements/wordpress
    container_name: wordpress
    expose:
      - "9000"
    volumes:
      - wp_content:/var/www/html
    env_file:
      - .env
    networks:
      - inception_network
    depends_on:
      - mariadb # depends_on can be done with a health check
    # restart:
    #   - "always"

  nginx:
    build: requirements/nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - inception_network
    depends_on:
      - mariadb # depends_on can be done with a health check
    # restart:
    #   - always

volumes:
  db_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/tomkrueger/data/mysql/data
  wp_content:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /Users/tomkrueger/data/wordpress/content

networks:
  inception_network:
