version: '3.9'

services:
  nginx:
    build: requirements/nginx/
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "./requirements/nginx/conf:/etc/nginx/conf.d:ro" # mounting the conf directory to the container with read only (:ro) access rights
    # depends_on:
    #   - mariadb
      # mariadb:
      #   condition: service_healthy

  # mariadb:
  #   build: requirements/mariadb
  #   container_name: mariadb
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - db_data:/var/lib/mysql
  #   networks:
  #     - inception_backend
  #   env_file:
  #     - .env # should mariadb parameters be included here or in requirements/mariadb/conf/ ?

volumes:
  db_data:
    driver: local
    driver_opts:
      o: 'bind'
      type: 'none'
      device: '/var/lib/mysql/inception_data'

networks:
  inception_backend: