version: '3.9'

services:
  nginx:
    build: requirements/nginx
    container_name: nginx
    depends_on:
      - mariadb # depends_on can be done with a health check
    ports:
      - "80:80"
      - "443:443"


  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    expose:
      - "3306"
    volumes:
      - db_data:/var/lib/mysql:delegated
    networks:
      - inception_network
    env_file:
      - .env

volumes:
  db_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $HOME/data/mysql
  wp_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: $HOME/data/wordpress

networks:
  inception_network:
